# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "hugo-tailwind-cookbook"
license = "THE BEER-WARE LICENSE"
licenselink = "https://github.com/sanddorn/hugo-tailwind-cookbook/blob/main/LICENSE"
description = "Digital cookbook template for Hugo built with TailwindCSS."
homepage = "https://github.com/sanddorn/hugo-tailwind-cookbook"
repo = "https://github.com/sanddorn/hugo-tailwind-cookbook"
tags = ["cookbook", "search", "recipes"]
features = ["documentation", "menu", "nested sections", "search"]

[author]
  name = "Nils Bokermann"
  homepage = "https://github.com/sanddorn/hugo-tailwind-cookbook"

[build]
  [[build.cachebusters]]
    source = 'layouts/.*'
    target = 'css'

[module]
  [module.hugoVersion]
    extended = true
    min = "0.145.0"
