# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "hugo-tailwind-cookbook"
license = "THE BEER-WARE LICENSE"
licenselink = "https://github.com/jtom38/hugo-cookbook/blob/master/LICENSE.md"
description = "Digital cookbook template for Hugo built with TailwindCSS."
homepage = "https://github.com/sanddorn/hugo-tailwind-cookbook"
repo = "https://github.com/sanddorn/hugo-tailwind-cookbook"
tags = ["cookbook", "search", "recipes"]
features = ["documentation", "menu", "nested sections", "search"]
min_version = 0.25

[author]
  name = "Nils Bokermann"
  homepage = "https://github.com/sanddorn/hugo-tailwind-cookbook"

[build]
  [[build.cachebusters]]
    source = 'layouts/.*'
    target = 'css'